export const de = {
  app: {
    name: "Kommunikationsplattform",
    tagline: "Sichere private Nachrichten",
  },
  login: {
    title: "Willkommen zurück",
    subtitle: "Melden Sie sich an, um auf Ihre Nachrichten zuzugreifen",
    email: "E-Mail-Adresse",
    emailPlaceholder: "ihre@email.de",
    password: "Passwort",
    passwordPlaceholder: "••••••••",
    submit: "Anmelden",
    loading: "Wird angemeldet...",
    error: "Ungültige E-Mail oder Passwort",
    demoHint: "Demo-Zugang: kunde@beispiel.de oder partner@beispiel.de",
    demoPassword: "Passwort: demo1234",
  },
  sidebar: {
    notifications: "Benachrichtigungen",
    noNotifications: "Keine Benachrichtigungen",
    logout: "Abmelden",
    online: "Online",
  },
  chat: {
    selectConversation: "Wählen Sie eine Unterhaltung",
    selectConversationHint:
      "Wählen Sie links eine Unterhaltung aus, um Nachrichten zu senden und zu empfangen.",
    typeMessage: "Nachricht eingeben...",
    send: "Senden",
    attachImage: "Bild anhängen",
    attachVideo: "Video anhängen",
    uploading: "Wird hochgeladen...",
    image: "Bild",
    video: "Video",
    you: "Sie",
    today: "Heute",
    yesterday: "Gestern",
    noMessages: "Noch keine Nachrichten. Schreiben Sie die erste Nachricht!",
  },
  notifications: {
    newMessage: "Neue Nachricht",
    newImage: "Neues Bild",
    newVideo: "Neues Video",
    from: "von",
  },
  time: {
    justNow: "Gerade eben",
    minutesAgo: (n: number) => `vor ${n} Min.`,
    hoursAgo: (n: number) => `vor ${n} Std.`,
    daysAgo: (n: number) => `vor ${n} Tagen`,
  },
  errors: {
    generic: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
    uploadFailed: "Upload fehlgeschlagen",
    fileTooLarge: "Datei ist zu groß (max. 50 MB)",
    invalidFileType: "Ungültiger Dateityp",
  },
};
