export const de = {
  app: {
    name: "Kommunikationsplattform",
    tagline: "Sichere private Nachrichten",
  },
  login: {
    title: "Willkommen zurück",
    subtitle: "Melden Sie sich an, um auf Ihre Nachrichten zuzugreifen",
    email: "E-Mail-Adresse",
    emailPlaceholder: "ihre@email.de",
    password: "Passwort",
    passwordPlaceholder: "••••••••",
    submit: "Anmelden",
    loading: "Wird angemeldet...",
    error: "Ungültige E-Mail oder Passwort",
    demoHint: "Demo-Zugang: kunde@beispiel.de oder partner@beispiel.de",
    demoPassword: "Passwort: demo1234",
  },
  sidebar: {
    notifications: "Benachrichtigungen",
    contacts: "Kontakte",
    noNotifications: "Keine Benachrichtigungen",
    noContacts: "Keine Kontakte",
    addContact: "Kontakt hinzufügen",
    addContactTitle: "Kontakt hinzufügen",
    selectContact: "Benutzer auswählen",
    add: "Hinzufügen",
    adding: "Wird hinzugefügt...",
    cancel: "Abbrechen",
    logout: "Abmelden",
    online: "Online",
  },
  contacts: {
    userNotFound: "Benutzer nicht gefunden",
    selectUser: "Bitte wählen Sie einen Benutzer aus",
    cannotAddSelf: "Sie können sich nicht selbst hinzufügen",
    alreadyAdded: "Dieser Kontakt ist bereits vorhanden",
    notAContact: "Sie können nur mit Ihren Kontakten chatten",
    addSuccess: "Kontakt hinzugefügt",
    addError: "Kontakt konnte nicht hinzugefügt werden",
    noUsersAvailable: "Keine weiteren Benutzer verfügbar",
  },
  chat: {
    selectConversation: "Wählen Sie einen Kontakt",
    selectConversationHint:
      "Wählen Sie links einen Kontakt aus, um eine Unterhaltung zu starten.",
    typeMessage: "Nachricht eingeben...",
    send: "Senden",
    attachImage: "Bild anhängen",
    attachVideo: "Video anhängen",
    uploading: "Wird hochgeladen...",
    image: "Bild",
    video: "Video",
    you: "Sie",
    today: "Heute",
    yesterday: "Gestern",
    noMessages: "Noch keine Nachrichten. Schreiben Sie die erste Nachricht!",
  },
  notifications: {
    newMessage: "Neue Nachricht",
    newImage: "Neues Bild",
    newVideo: "Neues Video",
    from: "von",
  },
  time: {
    justNow: "Gerade eben",
    minutesAgo: (n: number) => `vor ${n} Min.`,
    hoursAgo: (n: number) => `vor ${n} Std.`,
    daysAgo: (n: number) => `vor ${n} Tagen`,
  },
  errors: {
    generic: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
    uploadFailed: "Upload fehlgeschlagen",
    fileTooLarge: "Datei ist zu groß (max. 50 MB)",
    invalidFileType: "Ungültiger Dateityp",
  },
};
