export const de = {
  app: {
    name: "Kommunikationsplattform",
    tagline: "Sichere private Nachrichten",
  },
  login: {
    title: "Willkommen zurück",
    subtitle: "Melden Sie sich an, um auf Ihre Nachrichten zuzugreifen",
    email: "E-Mail-Adresse",
    emailPlaceholder: "ihre@email.de",
    password: "Passwort",
    passwordPlaceholder: "••••••••",
    submit: "Anmelden",
    loading: "Wird angemeldet...",
    error: "Ungültige E-Mail oder Passwort",
    demoHint: "Demo: kunde@beispiel.de, partner@beispiel.de oder admin@beispiel.de",
    demoPassword: "Passwort: demo1234 (Admin: admin1234)",
  },
  sidebar: {
    notifications: "Benachrichtigungen",
    contacts: "Kontakte",
    userManagement: "Benutzerverwaltung",
    noNotifications: "Keine Benachrichtigungen",
    noContacts: "Keine Kontakte",
    addContact: "Kontakt hinzufügen",
    addContactTitle: "Kontakt hinzufügen",
    selectContact: "Benutzer auswählen",
    add: "Hinzufügen",
    adding: "Wird hinzugefügt...",
    cancel: "Abbrechen",
    logout: "Abmelden",
    online: "Online",
  },
  contacts: {
    userNotFound: "Benutzer nicht gefunden",
    selectUser: "Bitte wählen Sie einen Benutzer aus",
    cannotAddSelf: "Sie können sich nicht selbst hinzufügen",
    alreadyAdded: "Dieser Kontakt ist bereits vorhanden",
    notAContact: "Sie können nur mit Ihren Kontakten chatten",
    addSuccess: "Kontakt hinzugefügt",
    addError: "Kontakt konnte nicht hinzugefügt werden",
    noUsersAvailable: "Keine weiteren Benutzer verfügbar",
  },
  admin: {
    title: "Benutzerverwaltung",
    subtitle: "Benutzer erstellen, bearbeiten und verwalten",
    unauthorized: "Keine Berechtigung",
    nameEmailRequired: "Name und E-Mail sind erforderlich",
    emailExists: "Diese E-Mail-Adresse wird bereits verwendet",
    passwordTooShort: "Passwort muss mindestens 6 Zeichen lang sein",
    userNotFound: "Benutzer nicht gefunden",
    cannotDeactivateSelf: "Sie können Ihr eigenes Konto nicht deaktivieren",
    cannotDemoteSelf: "Sie können Ihre eigene Administrator-Rolle nicht entfernen",
    cannotDeleteSelf: "Sie können Ihr eigenes Konto nicht löschen",
    createUser: "Benutzer erstellen",
    editUser: "Benutzer bearbeiten",
    allUsers: "Alle Benutzer",
    noUsers: "Keine Benutzer vorhanden",
    name: "Name",
    email: "E-Mail",
    password: "Passwort",
    role: "Rolle",
    roleUser: "Benutzer",
    roleAdmin: "Administrator",
    userType: "Typ",
    typeKunde: "Kunde",
    typePartner: "Partner",
    status: "Status",
    active: "Aktiv",
    inactive: "Inaktiv",
    generatePassword: "Passwort generieren",
    create: "Erstellen",
    creating: "Wird erstellt...",
    save: "Speichern",
    saving: "Wird gespeichert...",
    deactivate: "Deaktivieren",
    delete: "Löschen",
    activate: "Aktivieren",
    credentialsTitle: "Zugangsdaten",
    credentialsHint: "Bitte notieren Sie diese Zugangsdaten. Das Passwort wird nur einmal angezeigt.",
    close: "Schließen",
    createSuccess: "Benutzer erfolgreich erstellt",
    saveSuccess: "Benutzer erfolgreich aktualisiert",
    error: "Aktion fehlgeschlagen",
  },
  chat: {
    selectConversation: "Wählen Sie einen Kontakt",
    selectConversationHint:
      "Wählen Sie links einen Kontakt aus, um eine Unterhaltung zu starten.",
    typeMessage: "Nachricht eingeben...",
    send: "Senden",
    attachImage: "Bild anhängen",
    attachVideo: "Video anhängen",
    uploading: "Wird hochgeladen...",
    image: "Bild",
    video: "Video",
    you: "Sie",
    today: "Heute",
    yesterday: "Gestern",
    noMessages: "Noch keine Nachrichten. Schreiben Sie die erste Nachricht!",
  },
  calendar: {
    title: "Kalender",
    myCalendar: "Mein Kalender",
    calendarOf: (name: string) => `Kalender von ${name}`,
    openCalendar: "Kalender anzeigen",
    free: "Frei",
    busy: "Beschäftigt",
    addSlot: "Zeit eintragen",
    date: "Datum",
    from: "Von",
    to: "Bis",
    note: "Notiz (optional)",
    notePlaceholder: "z. B. Nur telefonisch erreichbar",
    save: "Speichern",
    saving: "Wird gespeichert...",
    delete: "Eintrag löschen",
    cancel: "Abbrechen",
    close: "Schließen",
    today: "Heute",
    prevWeek: "Vorherige Woche",
    nextWeek: "Nächste Woche",
    noSlotsDay: "Keine Einträge an diesem Tag",
    invalidTime: "Ungültige Zeitangabe",
    endBeforeStart: "Das Ende muss nach dem Beginn liegen",
    invalidType: "Ungültiger Eintragstyp",
    slotNotFound: "Eintrag nicht gefunden",
    saveError: "Eintrag konnte nicht gespeichert werden",
    legendHint: "Grün = frei, Grau = beschäftigt",
    prevMonth: "Vorheriger Monat",
    nextMonth: "Nächster Monat",
    noCalendar: "Dieser Benutzer hat keinen Kalender",
    onlyKunde: "Nur Kunden können Kalendereinträge erstellen",
    weekdaysShort: ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
  },
  gallery: {
    imageCounter: (current: number, total: number) =>
      `Bild ${current} von ${total}`,
    close: "Schließen",
    previous: "Vorheriges Bild",
    next: "Nächstes Bild",
    morePhotos: (n: number) => `+${n}`,
  },
  notifications: {
    newMessage: "Neue Nachricht",
    newImage: "Neues Bild",
    newVideo: "Neues Video",
    from: "von",
  },
  time: {
    justNow: "Gerade eben",
    minutesAgo: (n: number) => `vor ${n} Min.`,
    hoursAgo: (n: number) => `vor ${n} Std.`,
    daysAgo: (n: number) => `vor ${n} Tagen`,
  },
  errors: {
    generic: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
    uploadFailed: "Upload fehlgeschlagen",
    fileTooLarge: "Datei ist zu groß (max. 50 MB)",
    invalidFileType: "Ungültiger Dateityp",
  },
};
